name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t join-the-siege:test .

    - name: Run unit tests
      run: |
        docker run test-image pytest -v tests/ --ignore=tests/test_openai_clf.py